server:
  port: 9099
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springcloud-order
    username: root
    password: root
  application:
    name: order-service
mybatis:
  type-aliases-package: com.baidu.pojo
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
